apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: acrzh.azurecr.io/flask-app:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - secretRef:
                name: postgres-secrets
