apiVersion: v1
kind: Service
metadata:
    name: "aksdemo-728e"
    labels:
        app: "aksdemo-728e"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aksdemo-728e"